-- ============================================================
-- 14 CATEGORIAS DO LAYOUT DA OS + SEED MASSIVO DE EQUIPAMENTOS
-- ============================================================

-- Categorias exibidas como pills na tela de criação de OS
INSERT INTO public.categories (name, slug, icon, color) VALUES
  ('Consoles','consoles','Sliders','#3b82f6'),
  ('Caixas de Som','caixas-de-som','Speaker','#8b5cf6'),
  ('Rack / Amplificadores','rack-amplificadores','Zap','#f59e0b'),
  ('Microfones','microfones','Mic','#22c55e'),
  ('Mic Sem Fio / IEM','mic-sem-fio-iem','Radio','#10b981'),
  ('AC / Energia','ac-energia','Plug','#ef4444'),
  ('Cabos AC / Speakers / Sinal','cabos-ac-speakers-sinal','Cable','#64748b'),
  ('Multi-Cabos / Sub Snake','multi-cabos-sub-snake','Network','#0ea5e9'),
  ('Periféricos / Processadores','perifericos-processadores','Cpu','#a855f7'),
  ('DJ / Playback','dj-playback','Disc3','#06b6d4'),
  ('Back Line','back-line','Guitar','#f97316'),
  ('Estrutura / Rigging','estrutura-rigging','Anchor','#a855f7'),
  ('Acessórios / Suportes','acessorios-suportes','Package','#94a3b8'),
  ('Consumíveis / Fitas','consumiveis-fitas','Scissors','#737373')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color;

-- ============================================================
-- SEED EM MASSA — todos os equipamentos do PDF de OS
-- (idempotente: usa NOT EXISTS por nome+categoria)
-- ============================================================

WITH seed(name, category_slug, qty) AS (
  VALUES
    -- CONSOLES
    ('Digico SD9','consoles',1),
    ('Digico 338','consoles',0),
    ('Digidesign Venue','consoles',0),
    ('Yamaha Rivage PM5','consoles',0),
    ('Yamaha PM5D RH','consoles',1),
    ('Yamaha DM7','consoles',0),
    ('Yamaha DM3','consoles',0),
    ('Yamaha CL5','consoles',0),
    ('Yamaha CL3','consoles',5),
    ('Yamaha CL1','consoles',0),
    ('Yamaha TF5','consoles',0),
    ('Yamaha TF3','consoles',0),
    ('Yamaha TF1','consoles',0),
    ('Yamaha TF1 Rack','consoles',0),
    ('Yamaha M7CL','consoles',0),
    ('Yamaha LS9','consoles',0),
    ('Yamaha 01v 96','consoles',1),
    ('Yamaha MG166','consoles',0),
    ('Behringer X32','consoles',0),
    ('Midas 24','consoles',0),
    ('Behringer 12','consoles',0),
    ('Phonic 12','consoles',0),
    ('Phonic 08','consoles',0),

    -- CAIXAS DE SOM
    ('D&B T10','caixas-de-som',0),
    ('D&B B6','caixas-de-som',0),
    ('D&B T-Sub','caixas-de-som',0),
    ('L-Acoustic Kiva','caixas-de-som',0),
    ('L-Acoustic','caixas-de-som',0),
    ('Meyer MILO','caixas-de-som',8),
    ('Meyer Mina / P.A. Stack','caixas-de-som',0),
    ('Meyer CQ1','caixas-de-som',2),
    ('Meyer MSL-2','caixas-de-som',0),
    ('Meyer MSL-2A','caixas-de-som',0),
    ('Meyer MSW','caixas-de-som',0),
    ('Meyer MSW-2A','caixas-de-som',0),
    ('Meyer UPA-1P/DLY','caixas-de-som',0),
    ('Meyer UPM-1P/RT','caixas-de-som',0),
    ('Meyer UPJunior/FRT','caixas-de-som',0),
    ('Meyer HP 700 / Subs','caixas-de-som',0),
    ('Meyer HP 700','caixas-de-som',4),
    ('Meyer MM4','caixas-de-som',0),
    ('Meyer MM-4 / Fonte','caixas-de-som',4),
    ('Meyer lFC-1100','caixas-de-som',0),
    ('Behringer EUROLIVE','caixas-de-som',2),
    ('EAW KF850-VM','caixas-de-som',0),
    ('EAW SB850','caixas-de-som',0),
    ('EAW LA325','caixas-de-som',0),
    ('EAW SUB LA118A','caixas-de-som',0),
    ('FZ 102/RT','caixas-de-som',5),
    ('FZ102 HPA / P.A','caixas-de-som',6),
    ('FZ 18A Sub','caixas-de-som',2),
    ('FZ108/DLY','caixas-de-som',2),
    ('FZ 205/Copo','caixas-de-som',0),
    ('FZ 205/Alça','caixas-de-som',0),
    ('EV-1502','caixas-de-som',0),

    -- RACK / AMPLIFICADORES
    ('P6 HW','rack-amplificadores',0),
    ('KF-MX800','rack-amplificadores',0),
    ('MSL','rack-amplificadores',0),
    ('UPA stereo','rack-amplificadores',0),
    ('UPM','rack-amplificadores',0),
    ('4 Multi','rack-amplificadores',0),
    ('Lab Gruppen / com cabo','rack-amplificadores',0),

    -- MICROFONES
    ('Shure SM91B','microfones',1),
    ('Shure RE 20','microfones',0),
    ('Shure SM 98','microfones',4),
    ('Shure SM 81','microfones',2),
    ('Shure KSM 137','microfones',1),
    ('Shure KSM 9','microfones',0),
    ('Shure SM 87 BETA','microfones',0),
    ('Shure SM 58','microfones',0),
    ('Shure SM 57','microfones',4),
    ('Shure SM 58 Beta','microfones',6),
    ('Shure SM 57 Beta','microfones',0),
    ('Neumann KM184','microfones',3),
    ('AKG D 112','microfones',0),
    ('AKG 418','microfones',0),
    ('AKG C3000','microfones',0),
    ('AKG 419 / 519','microfones',0),
    ('AKG 414','microfones',0),
    ('Sennheiser E 906','microfones',0),
    ('Sennheiser MD 421','microfones',0),
    ('Sennheiser MD 604','microfones',3),
    ('Shotgun Sennheiser','microfones',0),
    ('Gooseneck Shure MX412','microfones',0),
    ('Lapela MK2 Gold','microfones',0),
    ('Head Set PG30','microfones',0),
    ('Countryman','microfones',0),
    ('Lapela 184','microfones',0),
    ('PZM JTS','microfones',0),

    -- MIC SEM FIO / IEM
    ('Shure UR4D-CH14','mic-sem-fio-iem',4),
    ('Hand UR4 SM87','mic-sem-fio-iem',0),
    ('Antena Omni','mic-sem-fio-iem',2),
    ('Cachimbo','mic-sem-fio-iem',0),
    ('Rack QLXD/CH4','mic-sem-fio-iem',1),
    ('Hand QLXD/SM86','mic-sem-fio-iem',4),
    ('Body Pack ULXD','mic-sem-fio-iem',0),
    ('Splitter BNC/T','mic-sem-fio-iem',0),
    ('Sennheiser G3 / Hands','mic-sem-fio-iem',0),
    ('PSM 600','mic-sem-fio-iem',0),
    ('PSM 900','mic-sem-fio-iem',4),
    ('Fone Shure SE5','mic-sem-fio-iem',4),
    ('Fone Shure SE3','mic-sem-fio-iem',0),
    ('Fone Shure SE535','mic-sem-fio-iem',0),
    ('Fone AKG K 414','mic-sem-fio-iem',2),
    ('Fone Koss Porta Pro','mic-sem-fio-iem',0),

    -- AC / ENERGIA
    ('Main Reversor','ac-energia',3),
    ('Sub Main Power 63 AH','ac-energia',0),
    ('Sub Main Power 150 AH','ac-energia',0),
    ('Main Power 5k DT/N1','ac-energia',1),
    ('Main Power 5k','ac-energia',0),
    ('Main Power 10k','ac-energia',0),
    ('Maxi Power 1000','ac-energia',0),
    ('Maxi Power 2000','ac-energia',0),
    ('Caixa Steck 32 x 32A','ac-energia',0),
    ('Caixa Steck 32 x 16A','ac-energia',1),
    ('Steck Back to Back 63','ac-energia',0),
    ('Prol. 32A 110v - 50m','ac-energia',0),
    ('Prol. 32A 110v - 25m','ac-energia',1),
    ('Prol. 32A 220v - 25m','ac-energia',2),
    ('Prol. 32A 220v - 50m','ac-energia',1),
    ('Prol. 32A 220v - 5m','ac-energia',0),
    ('Prolonga 63A - 25m','ac-energia',0),
    ('Canlock 150A 25m','ac-energia',0),
    ('Rabicho Tripolar','ac-energia',0),
    ('Rabicho 32A','ac-energia',1),
    ('Rabicho 63A','ac-energia',0),
    ('PP Amarela 10m','ac-energia',8),
    ('PP Vermelho 20m','ac-energia',10),
    ('Régua AC Pial PQ','ac-energia',2),
    ('Régua AC Pial GRD','ac-energia',2),
    ('Régua AM 16A PQ','ac-energia',2),
    ('Régua AM 16A GRD','ac-energia',2),
    ('Régua AZ 32A','ac-energia',2),
    ('Régua AM 32A','ac-energia',0),

    -- CABOS AC / SPEAKERS / SINAL
    ('Steck 32 - 3 Powercon','cabos-ac-speakers-sinal',0),
    ('Steck 32 - 2 Powercon','cabos-ac-speakers-sinal',0),
    ('Steck 32 - 3 Hubble','cabos-ac-speakers-sinal',0),
    ('Tripolar - Hubble 20F','cabos-ac-speakers-sinal',0),
    ('Tripolar - Powercon','cabos-ac-speakers-sinal',0),
    ('Hubble 20A - 20m','cabos-ac-speakers-sinal',0),
    ('Link Powercon 3M','cabos-ac-speakers-sinal',4),
    ('Link Powercon PQ','cabos-ac-speakers-sinal',0),
    ('KF 10M','cabos-ac-speakers-sinal',0),
    ('KF 25M','cabos-ac-speakers-sinal',0),
    ('SB 20M','cabos-ac-speakers-sinal',0),
    ('SB 10M','cabos-ac-speakers-sinal',0),
    ('Link XLR','cabos-ac-speakers-sinal',6),
    ('Sinal 05m','cabos-ac-speakers-sinal',10),
    ('Sinal 10m','cabos-ac-speakers-sinal',30),
    ('Sinal 20m','cabos-ac-speakers-sinal',10),
    ('Sinal 50m','cabos-ac-speakers-sinal',0),
    ('Speakon 05m','cabos-ac-speakers-sinal',0),
    ('Speakon 10m','cabos-ac-speakers-sinal',0),
    ('Speakon 20m','cabos-ac-speakers-sinal',0),
    ('Speakon 50m','cabos-ac-speakers-sinal',0),
    ('Can-Lok 25M','cabos-ac-speakers-sinal',0),

    -- MULTI-CABOS / SUB SNAKE
    ('Multi 12 vias 50m','multi-cabos-sub-snake',0),
    ('Multi 20 vias 70m','multi-cabos-sub-snake',0),
    ('Multi 27 vias c/ Split 30m','multi-cabos-sub-snake',1),
    ('Multi 56 vias c/ Split 70m','multi-cabos-sub-snake',1),
    ('Extensão W4/W4 - 15M','multi-cabos-sub-snake',0),
    ('Extensão W4/W4 - 100M','multi-cabos-sub-snake',0),
    ('Fan Outs / 58V','multi-cabos-sub-snake',0),
    ('Super Tour Whirlwind Setup','multi-cabos-sub-snake',0),
    ('Chuveirinho 2M','multi-cabos-sub-snake',0),
    ('Chuveirinho 15M','multi-cabos-sub-snake',0),
    ('Bandeja 15m','multi-cabos-sub-snake',3),
    ('Bandeja Multi-pino 12V/AF','multi-cabos-sub-snake',0),
    ('Multi-pino 12V/AF x XLR','multi-cabos-sub-snake',0),
    ('Multi-pino 12V/W1 x W1','multi-cabos-sub-snake',0),

    -- PERIFÉRICOS / PROCESSADORES
    ('Galileo 616','perifericos-processadores',1),
    ('Galileo 408','perifericos-processadores',0),
    ('M-Audio 26/26','perifericos-processadores',0),
    ('M-Audio 410','perifericos-processadores',1),
    ('M-Audio Mob Pré','perifericos-processadores',0),
    ('Behringer ADA 8000','perifericos-processadores',1),
    ('Isolador 1U','perifericos-processadores',2),
    ('Isolador 8U','perifericos-processadores',0),
    ('Press Box','perifericos-processadores',0),
    ('Lexicon PCM 80','perifericos-processadores',0),
    ('SPX 1000','perifericos-processadores',0),
    ('SPX 900','perifericos-processadores',0),
    ('DBX DDP','perifericos-processadores',0),
    ('Comp. BSS','perifericos-processadores',0),
    ('Gate BSS','perifericos-processadores',0),
    ('Presonus','perifericos-processadores',0),
    ('Yamaha 2031','perifericos-processadores',0),
    ('Comp DBX 160','perifericos-processadores',0),
    ('Avalon 737','perifericos-processadores',1),
    ('Adaptadores ABNT','perifericos-processadores',4),

    -- DJ / PLAYBACK
    ('Pioneer DJM 800','dj-playback',0),
    ('Pioneer DJM 600','dj-playback',1),
    ('Pioneer DJM 500','dj-playback',0),
    ('Pioneer CDJ 1000','dj-playback',0),
    ('Pioneer CDJ 400','dj-playback',0),
    ('Pioneer CDJ 200','dj-playback',2),
    ('Technics MKII','dj-playback',0),
    ('Denon 2300','dj-playback',0),
    ('CD Stanton','dj-playback',0),
    ('DVD / Pen Drive','dj-playback',0),
    ('Monitor 13"','dj-playback',0),
    ('Decoder Gefen','dj-playback',0),

    -- BACK LINE
    ('Marshall JCM 900 Combo','back-line',0),
    ('Jazz Chorus','back-line',0),
    ('Fender Twin Reverb','back-line',2),
    ('GK 800 Completo','back-line',1),
    ('GK 1001 Completo','back-line',0),
    ('Bateria Pearl Preta','back-line',1),
    ('Estante de Caixa / Extra','back-line',0),
    ('Estante de Prato / Extra','back-line',2),

    -- ESTRUTURA / RIGGING
    ('Yoke UPA','estrutura-rigging',0),
    ('Manilha PQ','estrutura-rigging',0),
    ('Manilha GRD','estrutura-rigging',0),
    ('Garra G','estrutura-rigging',0),
    ('Garra LP','estrutura-rigging',2),
    ('Talha 10mts','estrutura-rigging',0),
    ('Cano de 2MTS','estrutura-rigging',0),
    ('Cano Sup. Caixa','estrutura-rigging',2),
    ('Cinta Fly Talha 5MTS','estrutura-rigging',0),
    ('Cinta Catraca PQ','estrutura-rigging',0),
    ('Cinta Segurança','estrutura-rigging',0),
    ('Grip Flyt FZ','estrutura-rigging',0),
    ('Cabo de Aço PQ','estrutura-rigging',0),
    ('Parafuso Q30','estrutura-rigging',0),
    ('Gennie Nova 15MTS','estrutura-rigging',0),
    ('Aranha MILO VM','estrutura-rigging',2),
    ('Bumper Milo Original','estrutura-rigging',0),
    ('Bumper Mina','estrutura-rigging',0),
    ('Bumper KF','estrutura-rigging',0),
    ('Andaime 6 MT','estrutura-rigging',0),
    ('Corda 30MTS','estrutura-rigging',0),
    ('Capacete','estrutura-rigging',0),
    ('Barraca com Lona Lateral','estrutura-rigging',0),
    ('Praticável Pantográfico','estrutura-rigging',0),
    ('Lona Azul','estrutura-rigging',0),
    ('Trava / Chave','estrutura-rigging',0),
    ('Suporte FZ205','estrutura-rigging',0),
    ('Gaveteiro GRD','estrutura-rigging',0),
    ('Gaveteiro Milo','estrutura-rigging',0),
    ('Gaveteiro Melodie','estrutura-rigging',0),

    -- ACESSÓRIOS / SUPORTES
    ('Sim 3','acessorios-suportes',1),
    ('Monitor LCD','acessorios-suportes',1),
    ('Microfone DPA 4007','acessorios-suportes',0),
    ('Analisador de Espectro','acessorios-suportes',0),
    ('SoundGrid / Digico','acessorios-suportes',0),
    ('Digico Drack','acessorios-suportes',0),
    ('Cabo Cat5 - 75m','acessorios-suportes',2),
    ('Setup Intercom','acessorios-suportes',1),
    ('Fone Intercom','acessorios-suportes',4),
    ('Clearcom Sem Fio','acessorios-suportes',0),
    ('Fita Métrica','acessorios-suportes',0),
    ('Nível','acessorios-suportes',0),
    ('Passa Cabo','acessorios-suportes',0),
    ('Can Lock X Terminal','acessorios-suportes',5),
    ('Can Lock 25MTS','acessorios-suportes',5),
    ('Cabos Óticos','acessorios-suportes',2),
    ('Technics MK2','acessorios-suportes',0),
    ('Shells e Agulhas','acessorios-suportes',0),
    ('Luminária','acessorios-suportes',0),
    ('Back to Back - Speakon','acessorios-suportes',0),
    ('D.I. Countryman','acessorios-suportes',6),
    ('D.I. IMP2','acessorios-suportes',0),
    ('D.I. Radial','acessorios-suportes',0),
    ('Pedestal Girafa K&M','acessorios-suportes',12),
    ('Pedestal Pequeno','acessorios-suportes',4),
    ('Tripé','acessorios-suportes',8),
    ('Roteador Wi-Fi','acessorios-suportes',0),
    ('LOA Top Pré','acessorios-suportes',0),
    ('Antena UA In Ear','acessorios-suportes',1),
    ('Antena UA870 Direcional','acessorios-suportes',2),
    ('Antena H8089 Parabólica','acessorios-suportes',0),
    ('Cabo de Antena 10m','acessorios-suportes',3),
    ('Cabo de Antena 5m','acessorios-suportes',0),
    ('Booster Sennheiser','acessorios-suportes',0),
    ('Booster Shure','acessorios-suportes',0),
    ('Pedestal Mesa','acessorios-suportes',0),
    ('Adapt. RCA x XLR(M) Stereo','acessorios-suportes',2),
    ('Adapt. RCA x XLR(F)','acessorios-suportes',0),
    ('Adapt. P2 x RCA','acessorios-suportes',2),
    ('Adapt. RCA x P10 Duplo','acessorios-suportes',2),
    ('Adapt. P10 x XLR(M)','acessorios-suportes',4),
    ('Adapt. P10 x XLR(F)','acessorios-suportes',2),
    ('Adapt. XLR(M) x P02','acessorios-suportes',2),
    ('Adapt. P10 x P02','acessorios-suportes',2),
    ('Adapt. XLR M x M','acessorios-suportes',2),
    ('Adapt. XLR F x F','acessorios-suportes',2),
    ('Adapt. Split x XLR','acessorios-suportes',2),
    ('Adapt. Split 2(F) x 1(M)','acessorios-suportes',0),
    ('Adapt. P10 x P10','acessorios-suportes',6),
    ('Adapt. 8 x 8','acessorios-suportes',0),
    ('Adapt. 4 x 8','acessorios-suportes',0),
    ('Adapt. 4 x 4','acessorios-suportes',0),
    ('Splitter A/C','acessorios-suportes',12),
    ('Splitter Speakon','acessorios-suportes',0),

    -- CONSUMÍVEIS / FITAS
    ('Cartela 2 Pilhas AA','consumiveis-fitas',12),
    ('Cartela 2 Pilhas AA Usadas','consumiveis-fitas',12),
    ('Bateria 9V Nova','consumiveis-fitas',0),
    ('Bateria 9V Usada','consumiveis-fitas',0),
    ('Black Tape','consumiveis-fitas',2),
    ('Silver Tape','consumiveis-fitas',2),
    ('Fita Crepe','consumiveis-fitas',1),
    ('Pacote Hellerman GRD','consumiveis-fitas',1),
    ('Fita Isolante','consumiveis-fitas',4),
    ('Fita Isolante Amarela','consumiveis-fitas',2),
    ('Fita Isolante Branca','consumiveis-fitas',2)
)
INSERT INTO public.equipments (name, category_id, quantity, available_qty, status)
SELECT
  s.name,
  c.id,
  s.qty,
  s.qty,
  CASE WHEN s.qty > 0 THEN 'disponivel'::equipment_status ELSE 'disponivel'::equipment_status END
FROM seed s
JOIN public.categories c ON c.slug = s.category_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.equipments eq
  WHERE eq.name = s.name AND eq.category_id = c.id
);

-- Inicializa stock_levels para todos os equipamentos novos
INSERT INTO public.stock_levels (equipment_id, total_stock, available_stock)
SELECT id, COALESCE(quantity, 0), COALESCE(available_qty, 0)
FROM public.equipments
ON CONFLICT (equipment_id) DO UPDATE SET
  total_stock = EXCLUDED.total_stock,
  available_stock = EXCLUDED.available_stock,
  last_updated = now();
